# Generated by Django 4.2.10 on 2024-03-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training_systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="training_systems.product",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
