# Generated by Django 4.2.10 on 2024-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_systems", "0003_rename_product_id_group_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users_quantity",
            field=models.SmallIntegerField(default=0),
        ),
    ]
