# Generated by Django 4.2.10 on 2024-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_systems", "0004_group_users_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="users_quantity",
            field=models.SmallIntegerField(default=1),
        ),
    ]
